### ISSUE TITLE
Create webhooks for git repos

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#256]
This is to support triggering builds automagically in Jenkins.  Need to add hooks for 

Demandspike
NeverwinterDP
NeverwinterDP-Commons
Queuengin
Scribengin
Sparkngin
vagrant-flow

Documentation on how to do it is here: https://github.com/DemandCube/TeamWiki/wiki/Automated-Git-Push-Request-Testing-in-Jenkins  (You'll be looking at the second set of instructions at the bottom on how to configure the git repos)

**Comment by anthonyms** [comment]
While at it please include github-reporter. Currently it builds weekly

**Comment by smorin** [comment]
The github webhook has been added to BUT I am not sure the settings are 100% correct.

The wikipage of instructions shows a secret which I don't know what to put.  Additionally the default doesn't push "pull request" events, so how would jenkins be triggered on a "pull request"

DemandSpike
NeverwinterDP
NeverwinterDP-Commons
Queuengin
Scribengin
Sparkngin
vagrant-flow

Plus:
jstatsd
github-reporter

![screen shot 2014-07-31 at 7 34 56 am](https://cloud.githubusercontent.com/assets/124719/3765943/126c7034-18c0-11e4-9dd5-965f649ba225.png)

![screen shot 2014-07-31 at 7 35 31 am](https://cloud.githubusercontent.com/assets/124719/3765947/1c92c716-18c0-11e4-92f4-ab1ee11c114e.png)

```
<!DOCTYPE html><html><head>


    <title>Jenkins [Jenkins]</title><link rel="stylesheet" type="text/css" href="/static/4529e0a8/css/style.css" /><link rel="stylesheet" type="text/css" href="/static/4529e0a8/css/color.css" /><link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/static/4529e0a8/favicon.ico" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/4529e0a8";</script><script src="/static/4529e0a8/scripts/prototype.js" type="text/javascript"></script><script src="/static/4529e0a8/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/4529e0a8/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/4529e0a8/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/4529e0a8/scripts/yui/dom/dom-min.js"></script><script src="/static/4529e0a8/scripts/yui/event/event-min.js"></script><script src="/static/4529e0a8/scripts/yui/animation/animation-min.js"></script><script src="/static/4529e0a8/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/4529e0a8/scripts/yui/container/container-min.js"></script><script src="/static/4529e0a8/scripts/yui/connection/connection-min.js"></script><script src="/static/4529e0a8/scripts/yui/datasource/datasource-min.js"></script><script src="/static/4529e0a8/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/4529e0a8/scripts/yui/menu/menu-min.js"></script><script src="/static/4529e0a8/scripts/yui/element/element-min.js"></script><script src="/static/4529e0a8/scripts/yui/button/button-min.js"></script><script src="/static/4529e0a8/scripts/yui/storage/storage-min.js"></script><script src="/static/4529e0a8/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/4529e0a8/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" type="text/css" href="/static/4529e0a8/scripts/yui/container/assets/container.css" /><link rel="stylesheet" type="text/css" href="/static/4529e0a8/scripts/yui/assets/skins/sam/skin.css" /><link rel="stylesheet" type="text/css" href="/static/4529e0a8/scripts/yui/container/assets/skins/sam/container.css" /><link rel="stylesheet" type="text/css" href="/static/4529e0a8/scripts/yui/button/assets/skins/sam/button.css" /><link rel="stylesheet" type="text/css" href="/static/4529e0a8/scripts/yui/menu/assets/skins/sam/menu.css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><script src="/static/4529e0a8/scripts/yui/cookie/cookie-min.js"></script></head><body id="jenkins jenkins-1.557" class="yui-skin-sam"><a href="#skip2content" class="skiplink">Skip to content</a><table id="header" cellpadding="0" cellspacing="0" width="100%" border="0"><tr><td id="top-panel" colspan="2"><table cellpadding="0" cellspacing="0" width="100%" border="0"><tr><td style="font-weight:bold; font-size: 2em;"><a id="jenkins-home-link" href="/"><img id="jenkins-home-icon" height="34" alt="title" width="139" src="/static/4529e0a8/images/title.png" /></a></td><td style="vertical-align: middle; text-align: right; padding-right: 1em;"><form style="position:relative;" name="search" action="/search/" class="no-json" method="get"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input id="search-box" placeholder="search" name="q" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JENKINS/Search+Box"><img height="16" alt="help for search" width="16" src="/static/4529e0a8/images/16x16/help.png" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></td><td id="login-field"><span> <a style="color:inherit" href="/login?from=%2Fgit%2FnotifyCommit"><b>log in</b></a>
    |
    <a href="/signup"><b>sign up</b></a></span></td></tr></table></td></tr><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/4529e0a8/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/4529e0a8/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a class="model-link inside" href="/">Jenkins</a></li><li class="children" href="/"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></table><table id="main-table" height="70%" style="background-image: url(/static/4529e0a8/images/jenkins.png);                background-repeat: no-repeat; background-position: bottom left;" width="100%" border="0"><tr><td id="side-panel" width="20%"><div id="navigation" style="min-height: 323px; height: auto !important; height: 323px;"><div class="task">


          <a class="task-icon-link" href="http://jenkins-ci.org/"><img height="24" style="margin: 2px;" alt="" width="24" class="task-icon" src="/static/4529e0a8/images/24x24/next.png" /></a> <a class="task-link" href="http://jenkins-ci.org/">Jenkins project</a></div><div class="task">


          <a class="task-icon-link" href="http://issues.jenkins-ci.org/"><img height="24" style="margin: 2px;" alt="" width="24" class="task-icon" src="/static/4529e0a8/images/24x24/gear2.png" /></a> <a class="task-link" href="http://issues.jenkins-ci.org/">Bug tracker</a></div><div class="task">


          <a class="task-icon-link" href="http://jenkins-ci.org/content/mailing-lists"><img height="24" style="margin: 2px;" alt="" width="24" class="task-icon" src="/static/4529e0a8/images/24x24/search.png" /></a> <a class="task-link" href="http://jenkins-ci.org/content/mailing-lists">Mailing Lists</a></div><div class="task">


          <a class="task-icon-link" href="https://twitter.com/jenkinsci"><img height="24" style="margin: 2px;" alt="" width="24" class="task-icon" src="/static/4529e0a8/images/24x24/user.png" /></a> <a class="task-link" href="https://twitter.com/jenkinsci">Twitter: @jenkinsci</a></div></div></td><td id="main-panel" width="80%" height="100%"><a name="skip2content"></a><h1 style="text-align: center"><img height="179" width="154" src="/static/4529e0a8/images/rage.png" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://issues.jenkins-ci.org/">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="http://jenkins-ci.org/content/mailing-lists">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">javax.servlet.ServletException: java.lang.NullPointerException
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
    at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:390)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
    at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:174)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ApiTokenFilter.doFilter(ApiTokenFilter.java:74)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at hudson.plugins.git.GitStatus$JenkinsAbstractProjectListener.onNotifyCommit(GitStatus.java:271)
    at hudson.plugins.git.GitStatus.doNotifyCommit(GitStatus.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:120)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
    ... 64 more
</pre></div></td></tr></table><table width="100%"><tr><td id="footer"><span style="padding-right:2em; color:gray">
          Page generated:
          Jul 31, 2014 10:26:43 AM</span><span style="padding-right:2em"><a href="api/">REST API</a></span><a href="http://jenkins-ci.org/">Jenkins ver. 1.557</a></td></tr></table><div id="l10n-dialog" class="dialog"></div><div id="l10n-footer" style="display:none; float:left"><a href="#" onclick="return showTranslationDialog();"><img src="/static/4529e0a8/plugin/translation/flags.png" />
      Help us localize this page
    </a></div><script>var footer = document.getElementById('l10n-footer');
    var f = document.getElementById('footer');
    f.insertBefore(footer,f.firstChild);
    footer.style.display="block";

    var translation={}; 
    translation.bundles = "Xzhmhu1/fCx7x9QxJLG3V4c1qvRRROQCCqVs0qgtT3c8Rtaqn/VWEzehTGKaBB17XgVcsYKvWe3LzYV+/vc0n0fWRJ4H2tUtfV62NdxDBb0sLZEoUd5mmBn4d5jwevxRKh0rca+qq+Sl20END7af1crw+qyXW8z1FRW9gKG7oglW6sXepCqBOvwNJ1rlaWN6r2lFWv6NAXNKmfxvvoGSEAfkapDBnsDMUu2s+wN5c3EKjHZ9d3DVzQvVXaVQpp6ryZZPrb6xBi/L7sW0WFblQwDfeM60Q/UQ5tEWNLGhBNshc4bV469Oiyom/k3ZUWCdKQskEmYHAiNygAqHUI4EwozyzLaXXJH3qdPoCkgWQBumULkMojiDykNcCB93OhRoJXhvFeKo/YVEF/gMSxYVtjB8jRHGoKjGrNitlhg1I9RhPSYpqoqHTTfM/HCsmRUKgf9wWVcf1CTLU8OtYDw0wlkHhJgEU6v3h4APuufThI4l59GzfTy5wC18inpYOPjc5nquERg+EGecd9ktL6T3+g==";
    translation.detectedLocale = "";

    function showTranslationDialog() {
      if(!translation.launchDialog)
        loadScript("/static/4529e0a8/plugin/translation/dialog.js");
      else
        translation.launchDialog();
      return false; 
    }</script></body></html>
```

**Comment by KingOfPoptart** [comment]
1. leave the secret as the default, you don't have to set anything.  I'll update the documentation.
2. pull requests are all taken care of via a different mechanism.
