### ISSUE TITLE
Run the kafka stability check tools

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#486]
1.  Make sure with Richard to check in the scribengin.sh script and it should deploy the release to /opt/scribengin
2. Create the command /opt/cluster.sh kafka start --with-zookeeper. This command should launch the zookeeper and kafka only
3. Check, update the script  /opt/scribengin/tools/kafka/kafka.sh to make sure that you run the stability check tool(you may need to reconfigure the libs classpath), send and consume at least 1000 messages. You can check the class StabilityCheckTool in the kafka project for the available options. The class should run with the default parameters anyway.

**Comment by tuan08** [comment]
I am not sure it is you or Peter will work on this.  If Peter work on the failure simulation scenario. Then probably you should work this

**Comment by KingOfPoptart** [comment]
Item 1 done
2.  /opt/cluster.sh kafka start --with-zookeeper  -> done

**Comment by KingOfPoptart** [comment]
Problem 1 - if the topic already exists, you get an error, have to pick a new one every time.  Should we delete the topic and recreate it, or automatically do something like "hello" topic exists, so loop until a new topic can be found like "hello-1" or "hello-2"

Problem 2 - Getting an exception while reading, need to figure out what's wrong

```
neverwinterdp@hadoop-master:/opt/scribengin/tools/kafka$ ./kafka.sh test stability --zk-connect zookeeper-1
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
/usr/lib/jvm/java-7-openjdk-amd64/bin/java -Djava.ext.dirs=/opt/scribengin/libs -Xshare:auto -Xms128m -Xmx1536m -XX:-UseSplitVerifier -Dapp.dir=/opt/scribengin -Duser.dir=/opt/scribengin  com.neverwinterdp.kafka.tool.StabilityCheckTool "--zk-connect zookeeper-1"
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" kafka.common.TopicExistsException: Topic "hello" already exists.
    at kafka.admin.AdminUtils$.createOrUpdateTopicPartitionAssignmentPathInZK(AdminUtils.scala:187)
    at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:172)
    at kafka.admin.AdminUtils.createTopic(AdminUtils.scala)
    at com.neverwinterdp.kafka.tool.KafkaTool.createTopic(KafkaTool.java:84)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool.run(StabilityCheckTool.java:82)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool.run(StabilityCheckTool.java:66)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool.main(StabilityCheckTool.java:193)
neverwinterdp@hadoop-master:/opt/scribengin/tools/kafka$ ./kafka.sh test stability --zk-connect zookeeper-1 --topic hello1
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
/usr/lib/jvm/java-7-openjdk-amd64/bin/java -Djava.ext.dirs=/opt/scribengin/libs -Xshare:auto -Xms128m -Xmx1536m -XX:-UseSplitVerifier -Dapp.dir=/opt/scribengin -Duser.dir=/opt/scribengin  com.neverwinterdp.kafka.tool.StabilityCheckTool "--zk-connect zookeeper-1 --topic hello1"
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.Exception: TODO: handle the error, reset the consumer....
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:109)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool$PartitionMessageReader.run(StabilityCheckTool.java:171)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: TODO: handle the error, reset the consumer....
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:109)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool$PartitionMessageReader.run(StabilityCheckTool.java:171)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: TODO: handle the error, reset the consumer....
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:109)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool$PartitionMessageReader.run(StabilityCheckTool.java:171)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: TODO: handle the error, reset the consumer....
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:109)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool$PartitionMessageReader.run(StabilityCheckTool.java:171)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: TODO: handle the error, reset the consumer....
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:109)
    at com.neverwinterdp.kafka.tool.StabilityCheckTool$PartitionMessageReader.run(StabilityCheckTool.java:171)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
  Partition   Write   Read
  ---------------------------
  0           97      0
  1           97      0
  2           97      0
  3           97      0
  4           97      0

```
