### ISSUE TITLE
[Scribengin] Review Kafka partition reader exception

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#561]
Execute '/opt/kafka/bin/kafka-server-stop.sh' On  kafka-3
........................................................
FetchOperation try 1 error: null
FetchOperation try 2 error: null
FetchOperation try 3 error: null
java.nio.channels.ClosedChannelException
    at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
    at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:78)
    at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:68)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:112)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:112)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:112)
    at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:111)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:111)
    at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:111)
    at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
    at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:110)
    at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:47)
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader$FetchOperation.execute(KafkaPartitionReader.java:216)
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader$FetchOperation.execute(KafkaPartitionReader.java:196)
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.execute(KafkaPartitionReader.java:160)
    at com.neverwinterdp.kafka.consumer.KafkaPartitionReader.fetch(KafkaPartitionReader.java:100)
    at com.neverwinterdp.kafka.tool.KafkaMessageCheckTool.check(KafkaMessageCheckTool.java:120)
    at com.neverwinterdp.kafka.tool.KafkaMessageCheckTool.run(KafkaMessageCheckTool.java:90)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tuan08** [comment]
This bug is happened when retry is too fast while the kafka partition leader status is not updated in the zookeeper while the leader is already disconnected or crashed. Need to figure out a way to wait to detect the leader change
