### ISSUE TITLE
Enhance ability to launch Kafka/Zookeeper from hostmachine

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#617]
It would be nice if we could launch kafka/zookeeper without ssh'ing onto hadoop-master.

Currently if I run from my host box (Not a docker image) - I get an error if I try to launch zk/kafka because I don't have a config file locally.  Is there a way around this?  What are your thoughts?  Let's discuss before you move forward.

```
rcduar@appleTarts:cluster $ ./clusterCommander.py kafka --start zookeeper --start
Traceback (most recent call last):
  File "./clusterCommander.py", line 343, in <module>
    mastercommand()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 962, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "./clusterCommander.py", line 179, in kafka
    cluster.startKafka()
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 105, in startKafka
    return self.startProcess("kafka")
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 42, in startProcess
    server.startProcess(processName, self.paramDict, setupClusterEnv)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/Server.py", line 35, in startProcess
    self.processes[key].setupClusterEnv(paramDict)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/process/Process.py", line 101, in setupClusterEnv
    for line in open(paramDict["server_config"]).readlines():
IOError: [Errno 2] No such file or directory: u'/opt/kafka/config/default.properties'
```

**Comment by KingOfPoptart** [comment]
Fix: let's make the error more friendly and more descriptive of what to do.

**Comment by KingOfPoptart** [comment]
Kafka is good,

Just took a look at launching ZK, same problem

```
rcduar@appleTarts:cluster $ ./clusterCommander.py zookeeper --force-stop --clean --start
Killing zookeeper on zookeeper-2
Killing zookeeper on zookeeper-1
Cleaning data of zookeeper on zookeeper-2
Cleaning data of zookeeper on zookeeper-1
Traceback (most recent call last):
  File "./clusterCommander.py", line 350, in <module>
    mastercommand()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 962, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "./clusterCommander.py", line 218, in zookeeper
    cluster.startZookeeper()
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 103, in startZookeeper
    return self.startProcess("zookeeper")
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 43, in startProcess
    server.startProcess(processName, self.paramDict, setupClusterEnv)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/Server.py", line 35, in startProcess
    self.processes[key].setupClusterEnv(paramDict)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/process/Process.py", line 139, in setupClusterEnv
    for line in open(self.zoo_cfg_path).readlines():
IOError: [Errno 2] No such file or directory: '/opt/zookeeper/conf/zoo_sample.cfg'
```

**Comment by jeroldleslie** [comment]
huh. I do fix  this.

**Comment by KingOfPoptart** [comment]
I just ran this now:

```
rcduar@appleTarts:cluster $ git pull origin dev/master
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 73 (delta 22), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (73/73), done.
From http://github.com/DemandCube/Scribengin
 * branch            dev/master -> FETCH_HEAD
   08dd6a7..53469b8  dev/master -> origin/dev/master
Updating 8f02fc3..53469b8
Fast-forward
 V2/core/src/main/java/com/neverwinterdp/scribengin/client/shell/DataflowTestCommand.java          |  1 -
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/DataflowTest.java                | 11 +----------
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/HDFSDataflowSourceGenerator.java |  5 +----
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/HDFSDataflowTest.java            | 10 ++++++++--
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/HDFSToKafkaDataflowTest.java     | 14 +++++++++-----
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/KafkaDataflowTest.java           |  8 ++++++++
 V2/core/src/main/java/com/neverwinterdp/scribengin/dataflow/test/KafkaToHdfsDataflowTest.java     |  9 +++++++++
 V2/core/src/test/java/com/neverwinterdp/scribengin/dataflow/DataflowHdfsToHdfsUnitTest.java       |  5 +++--
 V2/core/src/test/java/com/neverwinterdp/scribengin/dataflow/DataflowHdfsToKafkaUnitTest.java      |  9 ++++++---
 V2/core/src/test/java/com/neverwinterdp/scribengin/dataflow/DataflowKafkaToHdfsUnitTest.java      |  3 ++-
 V2/core/src/test/java/com/neverwinterdp/scribengin/dataflow/DataflowKafkaToKafkaUnitTest.java     | 17 +----------------
 V2/docker/scribengin/integration-tests/Scribengin_Integration_HDFS_new.sh                         |  8 +++++++-
 V2/registry/src/main/java/com/neverwinterdp/registry/util/RegistryDebugger.java                   |  2 +-
 13 files changed, 56 insertions(+), 46 deletions(-)
rcduar@appleTarts:cluster $ ./clusterCommander.py kafka --start
Error: Invalid value for "--server-config": Path "/opt/kafka/config/default.properties" does not exist.
Please make sure kafka's "<server_template_name>.properties" file is available in the hosting machine, and give the same path for "--server-config"
rcduar@appleTarts:cluster $ ./clusterCommander.py zookeeper --start
Traceback (most recent call last):
  File "./clusterCommander.py", line 361, in <module>
    mastercommand()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 962, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "./clusterCommander.py", line 229, in zookeeper
    cluster.startZookeeper()
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 107, in startZookeeper
    return self.startProcess("zookeeper")
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/ServerSet.py", line 43, in startProcess
    server.startProcess(processName, self.paramDict, setupClusterEnv)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/server/Server.py", line 35, in startProcess
    self.processes[key].setupClusterEnv(paramDict)
  File "/Users/rcduar/workspace/Scribengin/V2/tools/cluster/process/Process.py", line 139, in setupClusterEnv
    for line in open(self.zoo_cfg_path).readlines():
IOError: [Errno 2] No such file or directory: '/opt/zookeeper/conf/zoo_sample.cfg'
rcduar@appleTarts:cluster $
```
