### ISSUE TITLE
Review integration test

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#643]
The integration test fail , probably due to the process that print out the running status. It cannot detect, exist and cause the time out. Probably you we can detect when vm-master is no longer available then all the processes should terminate.

**Comment by KingOfPoptart** [comment]
If you take a look at the results here - 

http://jenkinsdp.do.demandcube.com:8080/view/Integration%20Tests%20Dev/job/Scribengin_Integration_Tests_HDFS_To_Kafka_Dev/26/console

It looks like scribengin isn't being launched successfully.

```
Starting scribengin on hadoop-worker-1
Role           Hostname         ProcessIdentifier    ProcessID    HomeDir                          Status
-------------  ---------------  -------------------  -----------  -------------------------------  --------
hadoop-master  hadoop-master
                                NameNode             170          /opt/hadoop                      Running
                                SecondaryNameNode    289          /opt/hadoop                      Running
                                ResourceManager      388          /opt/hadoop                      Running
hadoop-worker  hadoop-worker-1
                                NodeManager          261          /opt/hadoop                      Running
                                DataNode             135          /opt/hadoop                      Running
hadoop-worker  hadoop-worker-3
                                vm-master-1          1606         /opt/scribengin/scribengin/bin/  Running
                                NodeManager          246          /opt/hadoop                      Running
                                DataNode             121          /opt/hadoop                      Running
hadoop-worker  hadoop-worker-2
                                NodeManager          253          /opt/hadoop                      Running
                                DataNode             128          /opt/hadoop                      Running
kafka          kafka-3
                                Kafka                67           /opt/kafka                       Running
kafka          kafka-1
                                Kafka                64           /opt/kafka                       Running
kafka          kafka-2
                                Kafka                63           /opt/kafka                       Running
zookeeper      zookeeper-1
                                QuorumPeerMain       91           /opt/zookeeper                   Running
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
type class com.neverwinterdp.scribengin.client.shell.ScribenginCommand$Info
Scribengin Info
***************
Exception in thread "main" com.neverwinterdp.registry.RegistryException: Get node children error
    at com.neverwinterdp.registry.zk.RegistryImpl.toRegistryException(RegistryImpl.java:492)
    at com.neverwinterdp.registry.zk.RegistryImpl.getChildren(RegistryImpl.java:253)
    at com.neverwinterdp.registry.zk.RegistryImpl.getChildrenAs(RegistryImpl.java:284)
    at com.neverwinterdp.scribengin.ScribenginClient.getRunningDataflowDescriptor(ScribenginClient.java:64)
    at com.neverwinterdp.scribengin.client.shell.ScribenginCommand$Info.execute(ScribenginCommand.java:54)
    at com.neverwinterdp.vm.client.shell.Command.execute(Command.java:21)
    at com.neverwinterdp.vm.client.shell.Shell.execute(Shell.java:66)
    at com.neverwinterdp.vm.client.shell.Shell.execute(Shell.java:58)
    at com.neverwinterdp.scribengin.ShellMain.main(ShellMain.java:44)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /NeverwinterDP/scribengin/dataflows/running
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500)
    at com.neverwinterdp.registry.zk.RegistryImpl.getChildren(RegistryImpl.java:250)
    ... 7 more
```

This doesn't appear to be an issue that happens _every_ time, so for now I'm going to have clusterCommander output the stdout/stderr from the `shell.sh vm start` and `shell.sh scribengin start` commands and keep an eye on it.

**Comment by KingOfPoptart** [comment]
This one failed because of the reason you stated - not detecting that the test is done, I'll work on that now

http://jenkinsdp.do.demandcube.com:8080/view/Integration%20Tests%20Dev/job/Scribengin_Integration_Tests_Dataflow_Server_Failure_Dev/25/console
